name: .NET CI (Scraper)

on:
  push:
    branches: [ "main" ]
    paths:
      - "MDS.Runner.Scraper/**"
      - "MDS.Runner.Scraper.Test/**"
      - "MDS.Data/**"
      - "MeDeixaSaber.Core/**"
      - ".github/workflows/dotnet-ci-mds-runner-scraper.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "MDS.Runner.Scraper/**"
      - "MDS.Runner.Scraper.Test/**"
      - "MDS.Data/**"
      - "MeDeixaSaber.Core/**"
      - ".github/workflows/dotnet-ci-mds-runner-scraper.yml"
  workflow_dispatch:

concurrency:
  group: ci-scraper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/global.json
            **/NuGet.config

      - name: Restore
        run: dotnet restore MeDeixaSaber.sln

      - name: Build
        run: dotnet build MeDeixaSaber.sln -c Release --no-restore

      - name: Test (MDS.Runner.Scraper.Test) + coverage
        run: dotnet test MDS.Runner.Scraper.Test/MDS.Runner.Scraper.Test.csproj -c Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

      - name: ReportGenerator
        run: |
          dotnet tool update -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"Coverage" -reporttypes:"HtmlInline;Cobertura" || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-Scraper
          path: |
            TestResults/**/*.trx
            **/coverage.cobertura.xml
            Coverage/**
