name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build (solution inteira)
        run: dotnet build -c Release --no-restore

      - name: Testes (somente MDS.Tests) + cobertura
        run: dotnet test MDS.Tests/MDS.Tests.csproj -c Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx"

      - name: ReportGenerator (HTML + Cobertura)
        shell: bash
        run: |
          dotnet tool update -g dotnet-reportgenerator-globaltool
          export PATH="$PATH:$HOME/.dotnet/tools"
          reportgenerator \
            -reports:"**/coverage.cobertura.xml" \
            -targetdir:"Coverage" \
            -reporttypes:"HtmlInline;Cobertura"

      - name: Publicar artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            **/TestResults/**/*.trx
            **/coverage.cobertura.xml
            Coverage/**

      - name: CI OK
        run: echo "Build OK e testes de MDS.Tests executados ✅"
